# Generated by Django 4.2.13 on 2024-06-26 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),  # Account 모델을 정의한 마이그레이션 파일의 번호와 일치해야 합니다.
        ('food', '0001_initial'),     # Foodorders 모델을 정의한 마이그레이션 파일의 번호와 일치해야 합니다.
        ('drink', '0001_initial'),    # Drinkorders 모델을 정의한 마이그레이션 파일의 번호와 일치해야 합니다.
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='account.account')),
                ('foodorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, related_name='purchases', to='food.foodorders')),
                ('drinkorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, blank=True, related_name='purchases', to='drink.drinkorders')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
    ]
