# Generated by Django 5.0.6 on 2024-07-03 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("drinkorders", "0001_initial"),
        ("foodorders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "purchase_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase",
                        to="account.account",
                    ),
                ),
                (
                    "drinkorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase",
                        to="drinkorders.drinkorders",
                    ),
                ),
                (
                    "foodorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase",
                        to="foodorders.foodorders",
                    ),
                ),
            ],
            options={
                "db_table": "purchase",
            },
        ),
    ]
