# Generated by Django 5.0.6 on 2024-06-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drinkId', models.AutoField(primary_key=True, serialize=False)),
                ('drinkName', models.CharField(max_length=128)),
                ('drinkType', models.CharField(max_length=128)),
                ('drinkDescription', models.TextField()),
                ('drinkPrice', models.DecimalField(max_digits=10, decimal_places=2)),
                ('drinkRegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('drinkUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drink',
            },
        ),
    ]