# Generated by Django 5.0.6 on 2024-07-10 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drinkorders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drinkordersitem",
            old_name="price",
            new_name="drinkprice",
        ),
        migrations.RenameField(
            model_name="drinkordersitem",
            old_name="quantity",
            new_name="drinkquantity",
        ),
    ]
