# Generated by Django 5.0.6 on 2024-07-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("drink", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drinkcart",
            fields=[
                ("drinkcartId", models.AutoField(primary_key=True, serialize=False)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drinkcarts",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "db_table": "drinkcart",
            },
        ),
        migrations.CreateModel(
            name="DrinkcartItem",
            fields=[
                (
                    "drinkcartItemId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "drink",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drink.drink"
                    ),
                ),
                (
                    "drinkcart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="drinkcart.drinkcart",
                    ),
                ),
            ],
            options={
                "db_table": "drinkcart_item",
            },
        ),
    ]
