# Generated by Django 4.2.13 on 2024-06-19 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drink', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinkcart',
            fields=[
                ('drinkcartId', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinkcarts', to='account.account')),
            ],
            options={
                'db_table': 'drinkcart',
            },
        ),
        migrations.CreateModel(
            name='DrinkcartItem',
            fields=[
                ('drinkcartItemId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drinkcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drinkcart.drinkcart')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
            ],
            options={
                'db_table': 'drinkcart_item',
            },
        ),
    ]
