# Generated by Django 5.0.6 on 2024-06-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=128)),
                ('foodType', models.CharField(max_length=128)),
                ('foodDescription', models.TextField()),
                ('foodPrice', models.DecimalField(max_digits=10, decimal_places=2)),
                ('foodImage', models.CharField(max_length=100, null=True)),

                ('foodRegisteredDate', models.DateTimeField(auto_now_add=True)),
                ('foodUpdatedDate', models.DateTimeField(auto_now=True)),

            ],
            options={
                'db_table': 'food',
            },
        ),
    ]