# Generated by Django 5.0.6 on 2024-07-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("foodId", models.AutoField(primary_key=True, serialize=False)),
                ("foodName", models.CharField(max_length=128)),
                ("foodType", models.CharField(max_length=128)),
                ("foodDescription", models.TextField()),
                ("foodPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("foodImage", models.CharField(max_length=100, null=True)),
                ("foodRegisteredDate", models.DateTimeField(auto_now_add=True)),
                ("foodUpdatedDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "food",
            },
        ),
    ]
