# Generated by Django 5.0.6 on 2024-07-10 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodcart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodcartitem",
            old_name="price",
            new_name="foodprice",
        ),
        migrations.RenameField(
            model_name="foodcartitem",
            old_name="quantity",
            new_name="foodquantity",
        ),
    ]
