# Generated by Django 5.0.6 on 2024-07-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionManage",
            fields=[
                (
                    "subscriptionManageId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                (
                    "subscriptionManageRegisteredDate",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("subscriptionManageUpdatedDate", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_manage",
            },
        ),
    ]
