# Generated by Django 5.0.6 on 2024-07-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movieReleaseDate",
            field=models.DateField(),
        ),
    ]
