# Generated by Django 5.0.6 on 2024-07-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(max_length=64),
        ),
    ]
